config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  devise_for :users

  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, uniqueness: {case_sensitive: true}
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :title, :price, :description, presence: true
  validates :price, format: {with: /\A\d+(?:\.\d{0,2})?\z/}, numericality: {minimum: 0}

  def average_rating
    self.reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :rating, :content, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products

  validates :firstname, presence: true
  validates :lastname, presence: true

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :firstname << :lastname
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin!, only: [:new, :edit, :update, :destroy, :create]

  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin!
    authenticate_user!
    begin
      authorize category, :admin?
    rescue
      flash[:error] = "You have insufficient right to do this."
      redirect_to new_user_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
  end

  def show
  end

  def new
  end

  def edit
    begin
      authorize product, :admin?
    rescue
      flash[:error] = "You are not allowed to edit this product."
      redirect_to category_product_url(category, product)
    end
  end

  def create
    self.product = Product.new(product_params)

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    begin
      authorize self.product, :admin?
      if self.product.update(product_params)
        redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
      else
        render action: 'edit'
      end
    rescue NotAuthorizedError
      flash[:error] = "You are not allowed to edit this product."
      redirect_to category_product_url(category, product)
    end
  end

  # DELETE /products/1
  def destroy
    authorize product, :admin?
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params.merge(user: current_user))

    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th
    %th
    %th

  - categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category
      - if policy(category).admin?
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
      - else
        %td
        %td

%br

- if policy(Category.new).admin?
  = link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = category.name

%p
  - category.products.each do |product|
    = product.title

%p
  %h3 New product
  = render 'products/form'

- if policy(category).admin?
  = link_to 'Edit', edit_category_path(category)
  \|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/layouts/_navbar_links.html.haml
- if user_signed_in?
  = link_to 'Sign out', destroy_user_session_path, method: :delete
- else
  = link_to 'Sign up', new_user_registration_path
  |
  = link_to 'Sign in', new_user_session_path

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand Netguru Kraków Workshops 2014
        %p.navbar-text.navbar-right
          = render partial: 'layouts/navbar_links'
    .container-fluid
      .row
        .col-lg-12
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.price
      %td= link_to 'Show', category_product_path(product.category, product)
      %td= link_to 'Edit', edit_category_product_path(product.category, product)
      %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
%p#notice= notice
%p#error= flash[:error]

%p
  %b Title:
  = product.title
%p
  %b Description:
  = product.description
%p
  %b Price:
  = product.price

%p
  %b Category
  = product.category.name

%h3 Reviews
= render 'reviews/form'

= render reviews

= link_to 'Edit', edit_category_product_path(category.id, product.id)
\|
= link_to 'Back', category_products_path, class: 'btn btn-primary'

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/reviews/_review.html.haml
%p= review.content
%p
  %b= review.rating
  %em= review.author